ALTER TABLE "UCRFiling"
ADD COLUMN "customerPaidAmount" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "customerBalanceDue" DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN "customerCreditAmount" DECIMAL(10, 2) NOT NULL DEFAULT 0;
