ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'PENDING_STAFF_REVIEW';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'PENDING_TRUCKER_FINALIZATION';

ALTER TABLE "Truck"
ADD COLUMN "nickname" TEXT;

ALTER TABLE "IftaReport"
ADD COLUMN "submittedForReviewAt" TIMESTAMP(3),
ADD COLUMN "staffReviewedAt" TIMESTAMP(3),
ADD COLUMN "reviewNotes" TEXT;
